FROM node:24.18.0-alpine3.24@sha256:a0b9bf06e4e6193cf7a0f58816cc935ff8c2a908f81e6f1a95432d679c54fbfd

ENV NODE_ENV=production \
  HOST=0.0.0.0 \
  PORT=8080 \
  DO_NOT_TRACK=1 \
  BL_ENABLE_OPENTELEMETRY=false \
  ABL_LOG_CONTENT=false
WORKDIR /opt/abl
COPY --chown=node:node app/ /opt/abl/
USER node
CMD ["node", "dist/index.js"]
