import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { build } from "esbuild";
import { format } from "prettier";

const repositoryRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const output = join(repositoryRoot, "skills/abl-league/dist/abl-runner.mjs");
await mkdir(dirname(output), { recursive: true });
await build({
  entryPoints: [join(repositoryRoot, "apps/participant-runner/src/cli.ts")],
  outfile: output,
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node24",
  legalComments: "none",
  minify: true,
  banner: {
    js: 'import { createRequire as __createRequire } from "node:module";const require=__createRequire(import.meta.url);',
  },
});
const bytes = await readFile(output);
const manifest = {
  version: 1,
  file: "skills/abl-league/dist/abl-runner.mjs",
  sha256: `0x${createHash("sha256").update(bytes).digest("hex")}`,
  bytes: bytes.byteLength,
  node: "24.18.0",
  adapters: ["COMMAND", "OPENAI_COMPATIBLE", "DETERMINISTIC_TEST"],
};
await writeFile(
  join(repositoryRoot, "skills/abl-league/dist/runner-manifest.json"),
  await format(JSON.stringify(manifest), { parser: "json" }),
);
await writeFile(
  join(repositoryRoot, "apps/public-api/src/runner-client-manifest.ts"),
  await format(
    `// Generated by scripts/build-runner-client.ts.\nexport const RUNNER_CLIENT_MANIFEST = ${JSON.stringify(manifest, null, 2)} as const;\n`,
    { parser: "typescript" },
  ),
);
