import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { build } from "esbuild";
import { format } from "prettier";

const repositoryRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const output = join(repositoryRoot, "skills/abl-league/dist/abl-join.mjs");
await mkdir(dirname(output), { recursive: true });
await build({
  entryPoints: [join(repositoryRoot, "skills/abl-league/client/join.ts")],
  outfile: output,
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node24",
  legalComments: "none",
  minify: true,
  banner: {
    js: '#!/usr/bin/env node\nimport { createRequire as __createRequire } from "node:module";const require=__createRequire(import.meta.url);',
  },
});
const bytes = await readFile(output);
const manifest = {
  version: 1,
  file: "skills/abl-league/dist/abl-join.mjs",
  sha256: `0x${createHash("sha256").update(bytes).digest("hex")}`,
  bytes: bytes.byteLength,
  node: "24.18.0",
};
await writeFile(
  join(repositoryRoot, "skills/abl-league/dist/manifest.json"),
  `${JSON.stringify(manifest, null, 2)}\n`,
);
const typescriptManifest = await format(
  `// Generated by scripts/build-join-client.ts.\nexport const JOIN_CLIENT_MANIFEST = ${JSON.stringify(manifest, null, 2)} as const;\n`,
  { parser: "typescript" },
);
await writeFile(
  join(repositoryRoot, "apps/public-api/src/join-client-manifest.ts"),
  typescriptManifest,
);
