// Generated by scripts/build-join-client.ts.
export const JOIN_CLIENT_MANIFEST = {
  version: 1,
  file: "skills/abl-league/dist/abl-join.mjs",
  sha256: "0x019036100eeca7fb63189347f0bf27a55d3dad6ae7c8db0c816da2acff6380df",
  bytes: 1093397,
  node: "24.18.0",
} as const;
