// Generated by scripts/build-join-client.ts.
export const JOIN_CLIENT_MANIFEST = {
  "version": 1,
  "file": "skills/abl-league/dist/abl-join.mjs",
  "sha256": "0xe36a007f1616b7d3bfe74b5b191e888bf6651a5302fc32459ba297662fc66423",
  "bytes": 1065935,
  "node": "24.18.0"
} as const;
