// Generated by scripts/build-join-client.ts.
export const JOIN_CLIENT_MANIFEST = {
  "version": 1,
  "file": "skills/abl-league/dist/abl-join.mjs",
  "sha256": "0xde21010543d11a94843e3f4209eadf63710d49e889d467d701d2bb2031789af9",
  "bytes": 1065799,
  "node": "24.18.0"
} as const;
