// Generated by scripts/build-runner-client.ts.
export const RUNNER_CLIENT_MANIFEST = {
  version: 1,
  file: "skills/abl-league/dist/abl-runner.mjs",
  sha256: "0x96fbdd60212d038779a0708e8249096fcdd4bbdbc21585643413748d4244bde8",
  bytes: 1179047,
  node: "24.18.0",
  adapters: ["COMMAND", "OPENAI_COMPATIBLE", "DETERMINISTIC_TEST"],
} as const;
